import {
  date,
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';
import { users } from './auth';
import { jobDescriptions } from './job';

// ---------------------------------------------------------------------------
// Enum
// ---------------------------------------------------------------------------

export const applicationStatusEnum = pgEnum('application_status', [
  'applied',
  'screening',
  'interview',
  'offer',
  'rejected',
  'withdrawn',
]);

export type ApplicationStatus = (typeof applicationStatusEnum.enumValues)[number];

// ---------------------------------------------------------------------------
// Table — applications
//
// Manual application tracking. One row per job application submitted.
// Optionally linked to a saved job_description row.
// Hard-deleted (no soft-delete) — no versioning needed.
// ---------------------------------------------------------------------------

export const applications = pgTable(
  'applications',
  {
    /** UUID v7 — generated by application layer before insert. */
    id: text('id').primaryKey(),

    /** FK to better-auth users table. Cascades on user delete. */
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /**
     * Optional link to a saved job description.
     * SET NULL when the JD is deleted — preserves the application record.
     */
    jobDescriptionId: text('job_description_id')
      .references(() => jobDescriptions.id, { onDelete: 'set null' }),

    /** Company name, e.g. "Google". Required. */
    company: text('company').notNull(),

    /** Role title, e.g. "Senior Backend Engineer". Required. */
    role: text('role').notNull(),

    /** Optional city/country or "Remote". */
    location: text('location'),

    /** Current stage in the hiring process. */
    status: applicationStatusEnum('status').notNull().default('applied'),

    /**
     * Date the application was submitted (YYYY-MM-DD).
     * Stored as a SQL date string — no timezone conversion needed.
     */
    appliedDate: date('applied_date').notNull(),

    /** Free-text notes — interview prep, recruiter name, salary range, etc. */
    notes: text('notes'),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    userIdx:   index('applications_user_idx').on(t.userId),
    statusIdx: index('applications_status_idx').on(t.status),
  }),
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type Application    = typeof applications.$inferSelect;
export type NewApplication = typeof applications.$inferInsert;
