import { integer, jsonb, pgEnum, pgTable, text, timestamp, index } from 'drizzle-orm/pg-core';
import { resumeVersions } from './resume';
import { jobDescriptions } from './job';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const scoringStatusEnum = pgEnum('scoring_status', [
  'pending', // row created, job not yet picked up
  'scoring', // worker-ai is running the two-step AI call
  'complete', // scores populated
  'failed', // score_error populated
]);

export type ScoringStatus = (typeof scoringStatusEnum.enumValues)[number];

export const optimizationStatusEnum = pgEnum('optimization_status', [
  'none', // no optimization requested yet
  'pending', // optimization job enqueued
  'optimizing', // worker-ai is running the optimizer
  'complete', // optimized_structured_data + optimization_change_log populated
  'failed', // optimization_error populated
]);

export type OptimizationStatus = (typeof optimizationStatusEnum.enumValues)[number];

// ---------------------------------------------------------------------------
// Table — ats_scores
//
// One row per (user-requested) scoring run. A user can request multiple scores
// for the same (resume, JD) pair (e.g. after editing the resume). Each run is
// independent — no unique constraint on (resume_version_id, job_description_id).
// ---------------------------------------------------------------------------

export const atsScores = pgTable(
  'ats_scores',
  {
    /** UUID v7 — generated by application before insert. */
    id: text('id').primaryKey(),

    /** FK to resume_versions. Cascades on resume delete. */
    resumeVersionId: text('resume_version_id')
      .notNull()
      .references(() => resumeVersions.id, { onDelete: 'cascade' }),

    /** FK to job_descriptions. Cascades on JD delete. */
    jobDescriptionId: text('job_description_id')
      .notNull()
      .references(() => jobDescriptions.id, { onDelete: 'cascade' }),

    // -----------------------------------------------------------------------
    // Scoring — original resume vs JD
    // -----------------------------------------------------------------------

    scoringStatus: scoringStatusEnum('scoring_status').notNull().default('pending'),

    /** Aggregate match score 0–100. Null until scoring is complete. */
    overallScore: integer('overall_score'),

    /**
     * Per-section breakdown scores 0–100 each.
     * Shape: { skills, experience, education, keywords }
     */
    sectionScores: jsonb('section_scores'),

    /** Keywords present in the JD but absent/weak in the resume. */
    keywordGaps: jsonb('keyword_gaps'),

    /** Keywords present in both the JD and the resume. */
    matchedKeywords: jsonb('matched_keywords'),

    /** Actionable improvement recommendations from the AI. */
    recommendations: jsonb('recommendations'),

    /** Human-readable error from a failed scoring attempt. */
    scoreError: text('score_error'),

    // -----------------------------------------------------------------------
    // Optimization (M3-C) — columns present now to avoid a second migration.
    // All nullable until the user requests optimization.
    // -----------------------------------------------------------------------

    optimizationStatus: optimizationStatusEnum('optimization_status').notNull().default('none'),

    /**
     * AI-rewritten ResumeData tailored to this JD.
     * Same shape as resume_versions.structured_data.
     */
    optimizedStructuredData: jsonb('optimized_structured_data'),

    /**
     * Log of changes made by the optimizer.
     * Shape: { section, field, original, optimized, reason }[]
     */
    optimizationChangeLog: jsonb('optimization_change_log'),

    /** Human-readable error from a failed optimization attempt. */
    optimizationError: text('optimization_error'),

    // -----------------------------------------------------------------------
    // Post-optimization re-score — populated by the optimize worker inline
    // immediately after optimization completes. Null if optimization has not
    // run or failed.
    // -----------------------------------------------------------------------

    /**
     * ATS overall score 0–100 computed against the OPTIMIZED resume.
     * Enables the before/after delta display (overallScore → optimizedOverallScore).
     */
    optimizedOverallScore: integer('optimized_overall_score'),

    /**
     * Per-section breakdown scores for the OPTIMIZED resume.
     * Shape: { skills, experience, education, keywords }
     * Enables side-by-side section diff in the UI.
     */
    optimizedSectionScores: jsonb('optimized_section_scores'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    /** List scores by JD efficiently (GET /v1/jobs/:id/scores). */
    jobDescriptionIdx: index('ats_scores_job_description_idx').on(t.jobDescriptionId),
    /** List scores by resume version for future cross-JD views. */
    resumeVersionIdx: index('ats_scores_resume_version_idx').on(t.resumeVersionId),
  }),
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type AtsScore = typeof atsScores.$inferSelect;
export type NewAtsScore = typeof atsScores.$inferInsert;
