/**
 * Extension schema — Phase 2 D2
 *
 * extension_tokens: one row per active extension installation.
 *
 * Token auth model (locked D2):
 *   Raw token  → 32-byte crypto.randomBytes() → returned ONCE, never stored
 *   token_hash → SHA-256 hex digest           → stored, indexed, used for lookup
 *   Lifetime   → 30-day sliding window (last_seen_at updated on each refresh)
 *   Revoke     → soft-delete via revoked_at; NULL = active
 */

import { index, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { users } from './auth';

// ---------------------------------------------------------------------------
// extension_tokens
// ---------------------------------------------------------------------------

export const extensionTokens = pgTable(
  'extension_tokens',
  {
    /** UUID v7 — generated by application layer before insert. */
    id: text('id').primaryKey(),

    /** FK to users. ON DELETE CASCADE — all tokens removed when user is deleted. */
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /**
     * SHA-256 hex digest of the raw bearer token.
     * UNIQUE: one hash per row, enables O(1) indexed lookup.
     * Raw token is never persisted — returned from exchange endpoint exactly once.
     */
    tokenHash: text('token_hash').notNull().unique(),

    /**
     * Sliding-window timestamp. Updated on every authenticated request.
     * Application layer treats a token as expired if:
     *   now() - last_seen_at > TOKEN_LIFETIME_MS (30 days)
     * No DB-level TTL — revoke is always explicit via the /revoke endpoint.
     */
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),

    /**
     * User-Agent string at mint time.
     * Displayed on /settings/devices for per-device identification (D14).
     */
    userAgent: text('user_agent'),

    /**
     * Soft-delete timestamp. NULL = active. Non-null = revoked.
     * All queries filter WHERE revoked_at IS NULL via the partial indexes
     * added manually to the migration after db:generate.
     */
    revokedAt: timestamp('revoked_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    /**
     * Index on user_id for listing a user's active tokens (/settings/devices).
     *
     * NOTE: The generated migration is patched after db:generate to add
     * WHERE revoked_at IS NULL (partial index). Drizzle schema retains this
     * definition for drift tracking on the column shape only.
     */
    userIdx: index('extension_tokens_user_idx').on(t.userId),
  }),
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type ExtensionToken    = typeof extensionTokens.$inferSelect;
export type NewExtensionToken = typeof extensionTokens.$inferInsert;
