import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { users } from './auth';

// ---------------------------------------------------------------------------
// Table — job_descriptions
// One row per job description saved by a user.
// Hard-deleted (no soft-delete) — cascades to ats_scores in M3-B.
// ---------------------------------------------------------------------------

export const jobDescriptions = pgTable('job_descriptions', {
  /** UUID v7 — generated by application before insert. */
  id: text('id').primaryKey(),

  /** FK to better-auth users table (text PK). Cascades on user delete. */
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  /** Optional human-readable label, e.g. "Senior Backend Engineer". */
  title: text('title'),

  /** Optional company name, e.g. "Stripe". */
  company: text('company'),

  /**
   * Raw job description text as pasted by the user.
   * Minimum 50 characters enforced at the API layer (Zod).
   * Maximum 50,000 characters — covers even the most verbose JDs.
   */
  content: text('content').notNull(),

  /** Optional source URL of the job posting. */
  url: text('url'),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),

  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Inferred types — used across API packages
// ---------------------------------------------------------------------------

export type JobDescription = typeof jobDescriptions.$inferSelect;
export type NewJobDescription = typeof jobDescriptions.$inferInsert;
