import {
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { users } from './auth';

// ---------------------------------------------------------------------------
// Enum — parse pipeline status
// ---------------------------------------------------------------------------

export const parseStatusEnum = pgEnum('parse_status', [
  'pending',   // row created, presigned URL issued
  'uploading', // browser is uploading to storage (reserved for future progress tracking)
  'uploaded',  // storage confirmed, job not yet queued
  'parsing',   // worker-ai picked up the job
  'complete',  // structured_data populated
  'failed',    // parse_error populated
]);

export type ParseStatus = (typeof parseStatusEnum.enumValues)[number];

// ---------------------------------------------------------------------------
// Table — resume_versions
// One row per upload. Multiple rows per user represent version history.
// ---------------------------------------------------------------------------

export const resumeVersions = pgTable(
  'resume_versions',
  {
    /** UUID v7 — generated by application before insert. */
    id: text('id').primaryKey(),

    /** FK to better-auth users table (text PK). Cascades on user delete. */
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),

    /**
     * Monotonically increasing per user (active rows only).
     * Assigned by the service: SELECT COALESCE(MAX(version_number), 0) + 1
     * WHERE deleted_at IS NULL.
     * The unique index below is partial — excludes soft-deleted rows — so
     * version numbers can be reused after a delete without constraint violations.
     */
    versionNumber: integer('version_number').notNull(),

    /** Object storage key, e.g. resumes/{userId}/{versionId}/{filename} */
    storageKey: text('storage_key').notNull(),

    /** Original filename as supplied by the browser. */
    fileName: text('file_name').notNull(),

    /** File size in bytes. Validated ≤ 10 MB before presign is issued. */
    fileSize: integer('file_size').notNull(),

    /** MIME type. One of: application/pdf | application/vnd.openxmlformats-officedocument.wordprocessingml.document | text/plain */
    mimeType: text('mime_type').notNull(),

    /** Current position in the parse pipeline. */
    parseStatus: parseStatusEnum('parse_status').notNull().default('pending'),

    /** Raw text extracted from the file by the parsing service. */
    rawText: text('raw_text'),

    /**
     * AI-extracted structured resume data.
     * Schema validated against ResumeDataSchema (packages/validation) before write.
     */
    structuredData: jsonb('structured_data'),

    /** Human-readable error from the last failed parse attempt. */
    parseError: text('parse_error'),

    /** Soft-delete. NULL = active. Non-null = logically deleted. */
    deletedAt: timestamp('deleted_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),

    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    /**
     * Partial unique index — version_number must be unique per user among
     * ACTIVE (non-deleted) rows only. Soft-deleted rows are excluded so that
     * version numbers can be reassigned after a delete without collisions.
     */
    userVersionUnique: uniqueIndex('resume_versions_user_version_unique')
      .on(t.userId, t.versionNumber)
      .where(sql`${t.deletedAt} is null`),
  }),
);

// ---------------------------------------------------------------------------
// Inferred types — used across API and worker packages
// ---------------------------------------------------------------------------

export type ResumeVersion    = typeof resumeVersions.$inferSelect;
export type NewResumeVersion = typeof resumeVersions.$inferInsert;
