import {
  pgEnum,
  pgTable,
  text,
  timestamp,
  boolean,
} from 'drizzle-orm/pg-core';
import { users } from './auth';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const planTypeEnum = pgEnum('plan_type', ['free', 'premium']);
export type PlanType = (typeof planTypeEnum.enumValues)[number];

export const subscriptionStatusEnum = pgEnum('subscription_status', [
  'active',
  'canceled',
  'past_due',
  'trialing',
  'incomplete',
]);
export type SubscriptionStatus = (typeof subscriptionStatusEnum.enumValues)[number];

export const usageEventTypeEnum = pgEnum('usage_event_type', [
  'ats_score',
  'optimization',
  'job_created',
]);
export type UsageEventType = (typeof usageEventTypeEnum.enumValues)[number];

// ---------------------------------------------------------------------------
// Table — subscriptions
//
// One row per user. Created lazily on first entitlement check.
// Free users have plan='free', stripe_* fields null.
// ---------------------------------------------------------------------------

export const subscriptions = pgTable('subscriptions', {
  /** UUID v7 — generated by application before insert. */
  id: text('id').primaryKey(),

  /** FK to better-auth users table. One subscription per user. */
  userId: text('user_id')
    .notNull()
    .unique()
    .references(() => users.id, { onDelete: 'cascade' }),

  /** Current plan. Defaults to free on creation. */
  plan: planTypeEnum('plan').notNull().default('free'),

  /** Stripe customer ID — null until user initiates checkout. */
  stripeCustomerId: text('stripe_customer_id').unique(),

  /** Stripe subscription ID — null for free plan. */
  stripeSubscriptionId: text('stripe_subscription_id').unique(),

  /** Stripe price ID — null for free plan. */
  stripePriceId: text('stripe_price_id'),

  /**
   * Subscription lifecycle status from Stripe.
   * Null for free plan (no Stripe subscription).
   */
  status: subscriptionStatusEnum('status'),

  /** Start of the current billing period. Null for free plan. */
  currentPeriodStart: timestamp('current_period_start', { withTimezone: true }),

  /** End of the current billing period. Null for free plan. */
  currentPeriodEnd: timestamp('current_period_end', { withTimezone: true }),

  /**
   * Whether the subscription is set to cancel at period end.
   * False for free plan.
   */
  cancelAtPeriodEnd: boolean('cancel_at_period_end').notNull().default(false),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type Subscription    = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;

// ---------------------------------------------------------------------------
// Table — usage_events
//
// Append-only log of metered actions. One row per action.
// Free tier limits are counted via date_trunc('month', created_at).
// Written BEFORE the action is enqueued to prevent race conditions.
// ---------------------------------------------------------------------------

export const usageEvents = pgTable('usage_events', {
  /** UUID v7 — generated by application before insert. */
  id: text('id').primaryKey(),

  /** FK to better-auth users table. */
  userId: text('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),

  /** The type of metered action. */
  eventType: usageEventTypeEnum('event_type').notNull(),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type UsageEvent    = typeof usageEvents.$inferSelect;
export type NewUsageEvent = typeof usageEvents.$inferInsert;
