/**
 * UserProfiles schema — Phase 2 D10
 *
 * Extensible profile table for user contact data consumed by the autofill engine.
 * One row per user (enforced by UNIQUE on user_id). Upsert pattern — created on
 * first save, updated on subsequent saves.
 *
 * Rationale for a separate table (not columns on users):
 *   - users is owned by better-auth; adding columns risks drift conflicts on upgrades.
 *   - user_profiles is application-owned and freely extensible.
 *   - JOIN is trivially cheap given the UNIQUE index on user_id.
 */

import { index, pgTable, text, timestamp } from 'drizzle-orm/pg-core';
import { users } from './auth';

// ---------------------------------------------------------------------------
// Table — user_profiles
// ---------------------------------------------------------------------------

export const userProfiles = pgTable(
  'user_profiles',
  {
    /** UUID v7 — generated by application before insert. */
    id: text('id').primaryKey(),

    /**
     * FK to better-auth users table (text PK). UNIQUE — one row per user.
     * ON DELETE CASCADE — profile removed when the user account is deleted.
     */
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' })
      .unique(),

    /** E.164 or free-form phone number. Nullable — optional for autofill. */
    phone: text('phone'),

    /** LinkedIn profile URL. Nullable. */
    linkedinUrl: text('linkedin_url'),

    /**
     * Personal website / portfolio URL.
     * Nullable — future: surfaced in autofill for "Website" fields.
     */
    websiteUrl: text('website_url'),

    /**
     * City, country, or "Remote".
     * Nullable — future: surfaced in autofill for "Location" fields.
     */
    location: text('location'),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    /**
     * Index for joining users → user_profiles.
     * UNIQUE constraint on user_id already creates an implicit index, but
     * an explicit named index keeps the audit trail clean and queryable via
     * Drizzle Studio.
     */
    userIdx: index('user_profiles_user_id_idx').on(t.userId),
  }),
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

/**
 * UserProfileRow — the DB row shape.
 * Named to avoid collision with UserProfile in apps/extension/src/shared/types.ts,
 * which is the assembled DTO returned to the extension.
 */
export type UserProfileRow = typeof userProfiles.$inferSelect;
export type NewUserProfileRow = typeof userProfiles.$inferInsert;
